export const attackDescriptions: { [key: string]: string[] } = {
  dagger: [
    'strikes swiftly with a dagger',
    'sneaks up and slashes with a dagger',
    'thrusts the dagger into the target',
    'quickly lunges forward with a dagger',
    'jabs the dagger into the enemy',
    'flashes the dagger with deadly precision',
  ],
  axe: [
    'swings an axe with great force',
    'chops down with an axe',
    'cleaves through the air with an axe',
    'brings the axe down in a powerful arc',
    'hacks at the target with brutal strength',
    'drives the axe deep into the opponent',
  ],
  sword: [
    'slashes skillfully with a sword',
    'lunges forward and strikes with a sword',
    'sweeps the sword in a wide arc',
    'pierces the target with a swift thrust',
    'whirls the sword overhead and strikes down',
    'executes a perfect parry followed by a counterattack',
  ],
  mace: [
    'bashes with a mace',
    'crushes the target with a mighty mace',
    'swings a mace, delivering a heavy blow',
    'smashes down with the weight of a mace',
    'swings the mace in a wide arc to knock back enemies',
    'delivers a devastating overhead strike with a mace',
  ],
  fire: [
    'ignites the target with a burst of fire',
    'launches a fireball that explodes on impact',
    'engulfs the target in flames',
    'summons a wall of fire to engulf the enemy',
    'unleashes a fiery breath that scorches the ground',
    'creates a ring of fire that traps the opponent',
  ],
  frost: [
    'freezes the target with a chilling blast',
    'envelops the target in icy tendrils',
    'shatters the ground with frost',
    'launches shards of ice that pierce the target',
    'encases the opponent in a block of ice',
    'creates a blizzard that hampers movement',
  ],
  arcane: [
    'unleashes a surge of arcane energy',
    'casts a powerful spell of arcane might',
    'strikes with mystical forces',
    'summons a vortex of arcane power',
    'releases a burst of energy that confounds the foe',
    'weaves a spell that disrupts reality itself',
  ],
  earth: [
    'smashes the ground, sending rocks flying',
    'bursts forth from the earth, striking the target',
    'slams the target with a fist of stone',
    'creates a tremor that destabilizes the enemy',
    'raises a wall of stone to shield and counterattack',
    'calls upon the earth to strike down the opponent',
  ],
  air: [
    'slices through the air with a gust of wind',
    'strikes with a powerful whirlwind',
    'unleashes a barrage of sharp winds',
    'creates a cyclone that pulls the enemy in',
    'fires a blast of compressed air that knocks back the target',
    'wraps the foe in a whirlwind, leaving them disoriented',
  ],
  bow: [
    'fires a precise arrow from a bow',
    'lets loose a volley of arrows',
    'draws back the bowstring and releases',
    'quickly fires a rapid succession of arrows',
    'aims carefully and shoots a critical arrow',
    'looses an arrow that strikes true and deep',
  ],
  crossbow: [
    'loads and fires a bolt from a crossbow',
    'unleashes a deadly bolt at high speed',
    'snaps the crossbow into action, hitting the target',
    'fires a precision bolt that pierces armor',
    'quickly reloads and fires another bolt',
    'sets a trap with a crossbow for a surprise attack',
  ],
  shield: [
    'smashes the opponent with the shield',
    'strikes the enemy with a powerful shield bash',
    'charges forward, using the shield to knock back the target',
    'swings the shield like a weapon, hitting the foe',
    'delivers a stunning blow with the edge of the shield',
    'launches a shield attack that disrupts the enemy’s balance',
  ],
  default: [
    'hits the target'
  ]
};