export type Portrait = {
  name: string,
  path: string,
  race: string
}

export type Race = Portrait[]

export const portraits: Record<string, Portrait[]> = {
  dwarf: [
    { name: 'Dwarf 1', path: 'dwarf1.png', race: 'dwarf' },
    { name: 'Dwarf 2', path: 'dwarf2.png', race: 'dwarf' },
    { name: 'Dwarf 3', path: 'dwarf3.png', race: 'dwarf' },
    { name: 'Dwarf 4', path: 'dwarf4.png', race: 'dwarf' },
    { name: 'Dwarf 5', path: 'dwarf5.png', race: 'dwarf' },
    { name: 'Dwarf 6', path: 'dwarf6.png', race: 'dwarf' },
    { name: 'Dwarf 7', path: 'dwarf7.png', race: 'dwarf' },
    { name: 'Dwarf 8', path: 'dwarf8.png', race: 'dwarf' },
    { name: 'Dwarf 9', path: 'dwarf9.png', race: 'dwarf' },
    { name: 'Dwarf 10', path: 'dwarf10.png', race: 'dwarf' },
    { name: 'Dwarf 11', path: 'dwarf11.png', race: 'dwarf' },
    { name: 'Dwarf 12', path: 'dwarf12.png', race: 'dwarf' },
    { name: 'Dwarf 13', path: 'dwarf13.png', race: 'dwarf' },
    { name: 'Dwarf 14', path: 'dwarf14.png', race: 'dwarf' },
    { name: 'Dwarf 15', path: 'dwarf15.png', race: 'dwarf' },
    { name: 'Dwarf 16', path: 'dwarf16.png', race: 'dwarf' },
    { name: 'Dwarf 17', path: 'dwarf17.png', race: 'dwarf' },
    { name: 'Dwarf 18', path: 'dwarf18.png', race: 'dwarf' },
    { name: 'Dwarf 19', path: 'dwarf19.png', race: 'dwarf' },
    { name: 'Dwarf 20', path: 'dwarf20.png', race: 'dwarf' },
    { name: 'Dwarf 21', path: 'dwarf21.png', race: 'dwarf' },
    { name: 'Dwarf 22', path: 'dwarf22.png', race: 'dwarf' },
    { name: 'Dwarf 23', path: 'dwarf23.png', race: 'dwarf' },
    { name: 'Dwarf 24', path: 'dwarf24.png', race: 'dwarf' },
    { name: 'Dwarf 25', path: 'dwarf25.png', race: 'dwarf' },
    { name: 'Dwarf 26', path: 'dwarf26.png', race: 'dwarf' },
    { name: 'Dwarf 27', path: 'dwarf27.png', race: 'dwarf' },
    { name: 'Dwarf 28', path: 'dwarf28.png', race: 'dwarf' },
    { name: 'Dwarf 29', path: 'dwarf29.png', race: 'dwarf' },
    { name: 'Dwarf 30', path: 'dwarf30.png', race: 'dwarf' },
    { name: 'Dwarf 31', path: 'dwarf31.png', race: 'dwarf' },
    { name: 'Dwarf 32', path: 'dwarf32.png', race: 'dwarf' },
    { name: 'Dwarf 33', path: 'dwarf33.png', race: 'dwarf' },
    { name: 'Dwarf 34', path: 'dwarf34.png', race: 'dwarf' },
    { name: 'Dwarf 35', path: 'dwarf35.png', race: 'dwarf' },
    { name: 'Dwarf 36', path: 'dwarf36.png', race: 'dwarf' },
    { name: 'Dwarf 37', path: 'dwarf37.png', race: 'dwarf' },
    { name: 'Dwarf 38', path: 'dwarf38.png', race: 'dwarf' },
    { name: 'Dwarf 39', path: 'dwarf39.png', race: 'dwarf' },
    { name: 'Dwarf 40', path: 'dwarf40.png', race: 'dwarf' },
    { name: 'Dwarf 41', path: 'dwarf41.png', race: 'dwarf' },
    { name: 'Dwarf 42', path: 'dwarf42.png', race: 'dwarf' },
    { name: 'Dwarf 43', path: 'dwarf43.png', race: 'dwarf' },
    { name: 'Dwarf 44', path: 'dwarf44.png', race: 'dwarf' },
    { name: 'Dwarf 45', path: 'dwarf45.png', race: 'dwarf' },
    { name: 'Dwarf 46', path: 'dwarf46.png', race: 'dwarf' },
    { name: 'Dwarf 47', path: 'dwarf47.png', race: 'dwarf' },
    { name: 'Dwarf 48', path: 'dwarf48.png', race: 'dwarf' },
  ],
  human: [
    { name: 'Human 1', path: 'human1.png', race: 'human' },
    { name: 'Human 2', path: 'human2.png', race: 'human' },
    { name: 'Human 3', path: 'human3.png', race: 'human' },
    { name: 'Human 4', path: 'human4.png', race: 'human' },
    { name: 'Human 5', path: 'human5.png', race: 'human' },
    { name: 'Human 6', path: 'human6.png', race: 'human' },
    { name: 'Human 7', path: 'human7.png', race: 'human' },
    { name: 'Human 8', path: 'human8.png', race: 'human' },
    { name: 'Human 9', path: 'human9.png', race: 'human' },
    { name: 'Human 10', path: 'human10.png', race: 'human' },
    { name: 'Human 11', path: 'human11.png', race: 'human' },
    { name: 'Human 12', path: 'human12.png', race: 'human' },
    { name: 'Human 13', path: 'human13.png', race: 'human' },
    { name: 'Human 14', path: 'human14.png', race: 'human' },
    { name: 'Human 15', path: 'human15.png', race: 'human' },
    { name: 'Human 16', path: 'human16.png', race: 'human' },
    { name: 'Human 17', path: 'human17.png', race: 'human' },
    { name: 'Human 18', path: 'human18.png', race: 'human' },
    { name: 'Human 19', path: 'human19.png', race: 'human' },
    { name: 'Human 20', path: 'human20.png', race: 'human' },
    { name: 'Human 21', path: 'human21.png', race: 'human' },
    { name: 'Human 22', path: 'human22.png', race: 'human' },
    { name: 'Human 23', path: 'human23.png', race: 'human' },
    { name: 'Human 24', path: 'human24.png', race: 'human' },
    { name: 'Human 25', path: 'human25.png', race: 'human' },
    { name: 'Human 26', path: 'human26.png', race: 'human' },
    { name: 'Human 27', path: 'human27.png', race: 'human' },
    { name: 'Human 28', path: 'human28.png', race: 'human' },
    { name: 'Human 29', path: 'human29.png', race: 'human' },
    { name: 'Human 30', path: 'human30.png', race: 'human' },
    { name: 'Human 31', path: 'human31.png', race: 'human' },
    { name: 'Human 32', path: 'human32.png', race: 'human' },
    { name: 'Human 33', path: 'human33.png', race: 'human' },
    { name: 'Human 34', path: 'human34.png', race: 'human' },
    { name: 'Human 35', path: 'human35.png', race: 'human' },
    { name: 'Human 36', path: 'human36.png', race: 'human' },
    { name: 'Human 37', path: 'human37.png', race: 'human' },
    { name: 'Human 38', path: 'human38.png', race: 'human' },
    { name: 'Human 39', path: 'human39.png', race: 'human' },
    { name: 'Human 40', path: 'human40.png', race: 'human' },
    { name: 'Human 41', path: 'human41.png', race: 'human' },
    { name: 'Human 42', path: 'human42.png', race: 'human' },
    { name: 'Human 43', path: 'human43.png', race: 'human' },
    { name: 'Human 44', path: 'human44.png', race: 'human' },
    { name: 'Human 45', path: 'human45.png', race: 'human' },
    { name: 'Human 46', path: 'human46.png', race: 'human' },
    { name: 'Human 47', path: 'human47.png', race: 'human' },
    { name: 'Human 48', path: 'human48.png', race: 'human' },
  ],
  halfling: [
    { name: 'Halfling 1', path: 'halfling1.png', race: 'halfling' },
    { name: 'Halfling 2', path: 'halfling2.png', race: 'halfling' },
    { name: 'Halfling 3', path: 'halfling3.png', race: 'halfling' },
    { name: 'Halfling 4', path: 'halfling4.png', race: 'halfling' },
    { name: 'Halfling 5', path: 'halfling5.png', race: 'halfling' },
    { name: 'Halfling 6', path: 'halfling6.png', race: 'halfling' },
    { name: 'Halfling 7', path: 'halfling7.png', race: 'halfling' },
    { name: 'Halfling 8', path: 'halfling8.png', race: 'halfling' },
    { name: 'Halfling 9', path: 'halfling9.png', race: 'halfling' },
    { name: 'Halfling 10', path: 'halfling10.png', race: 'halfling' },
    { name: 'Halfling 11', path: 'halfling11.png', race: 'halfling' },
    { name: 'Halfling 12', path: 'halfling12.png', race: 'halfling' },
    { name: 'Halfling 13', path: 'halfling13.png', race: 'halfling' },
    { name: 'Halfling 14', path: 'halfling14.png', race: 'halfling' },
    { name: 'Halfling 15', path: 'halfling15.png', race: 'halfling' },
    { name: 'Halfling 16', path: 'halfling16.png', race: 'halfling' },
    { name: 'Halfling 17', path: 'halfling17.png', race: 'halfling' },
    { name: 'Halfling 18', path: 'halfling18.png', race: 'halfling' },
    { name: 'Halfling 19', path: 'halfling19.png', race: 'halfling' },
    { name: 'Halfling 20', path: 'halfling20.png', race: 'halfling' },
    { name: 'Halfling 21', path: 'halfling21.png', race: 'halfling' },
    { name: 'Halfling 22', path: 'halfling22.png', race: 'halfling' },
    { name: 'Halfling 23', path: 'halfling23.png', race: 'halfling' },
    { name: 'Halfling 24', path: 'halfling24.png', race: 'halfling' },
    { name: 'Halfling 25', path: 'halfling25.png', race: 'halfling' },
    { name: 'Halfling 26', path: 'halfling26.png', race: 'halfling' },
    { name: 'Halfling 27', path: 'halfling27.png', race: 'halfling' },
    { name: 'Halfling 28', path: 'halfling28.png', race: 'halfling' },
    { name: 'Halfling 29', path: 'halfling29.png', race: 'halfling' },
    { name: 'Halfling 30', path: 'halfling30.png', race: 'halfling' },
    { name: 'Halfling 31', path: 'halfling31.png', race: 'halfling' },
    { name: 'Halfling 32', path: 'halfling32.png', race: 'halfling' },
    { name: 'Halfling 33', path: 'halfling33.png', race: 'halfling' },
    { name: 'Halfling 34', path: 'halfling34.png', race: 'halfling' },
    { name: 'Halfling 35', path: 'halfling35.png', race: 'halfling' },
    { name: 'Halfling 36', path: 'halfling36.png', race: 'halfling' },
    { name: 'Halfling 37', path: 'halfling37.png', race: 'halfling' },
    { name: 'Halfling 38', path: 'halfling38.png', race: 'halfling' },
    { name: 'Halfling 39', path: 'halfling39.png', race: 'halfling' },
    { name: 'Halfling 40', path: 'halfling40.png', race: 'halfling' },
    { name: 'Halfling 41', path: 'halfling41.png', race: 'halfling' },
    { name: 'Halfling 42', path: 'halfling42.png', race: 'halfling' },
    { name: 'Halfling 43', path: 'halfling43.png', race: 'halfling' },
    { name: 'Halfling 44', path: 'halfling44.png', race: 'halfling' },
    { name: 'Halfling 45', path: 'halfling45.png', race: 'halfling' },
    { name: 'Halfling 46', path: 'halfling46.png', race: 'halfling' },
    { name: 'Halfling 47', path: 'halfling47.png', race: 'halfling' },
    { name: 'Halfling 48', path: 'halfling48.png', race: 'halfling' },
  ],
  night_elf: [
    { name: 'Night Elf 1', path: 'night_elf1.png', race: 'night_elf' },
    { name: 'Night Elf 2', path: 'night_elf2.png', race: 'night_elf' },
    { name: 'Night Elf 3', path: 'night_elf3.png', race: 'night_elf' },
    { name: 'Night Elf 4', path: 'night_elf4.png', race: 'night_elf' },
    { name: 'Night Elf 5', path: 'night_elf5.png', race: 'night_elf' },
    { name: 'Night Elf 6', path: 'night_elf6.png', race: 'night_elf' },
    { name: 'Night Elf 7', path: 'night_elf7.png', race: 'night_elf' },
    { name: 'Night Elf 8', path: 'night_elf8.png', race: 'night_elf' },
    { name: 'Night Elf 9', path: 'night_elf9.png', race: 'night_elf' },
    { name: 'Night Elf 10', path: 'night_elf10.png', race: 'night_elf' },
    { name: 'Night Elf 11', path: 'night_elf11.png', race: 'night_elf' },
    { name: 'Night Elf 12', path: 'night_elf12.png', race: 'night_elf' },
    { name: 'Night Elf 13', path: 'night_elf13.png', race: 'night_elf' },
    { name: 'Night Elf 14', path: 'night_elf14.png', race: 'night_elf' },
    { name: 'Night Elf 15', path: 'night_elf15.png', race: 'night_elf' },
    { name: 'Night Elf 16', path: 'night_elf16.png', race: 'night_elf' },
    { name: 'Night Elf 17', path: 'night_elf17.png', race: 'night_elf' },
    { name: 'Night Elf 18', path: 'night_elf18.png', race: 'night_elf' },
    { name: 'Night Elf 19', path: 'night_elf19.png', race: 'night_elf' },
    { name: 'Night Elf 20', path: 'night_elf20.png', race: 'night_elf' },
    { name: 'Night Elf 21', path: 'night_elf21.png', race: 'night_elf' },
    { name: 'Night Elf 22', path: 'night_elf22.png', race: 'night_elf' },
    { name: 'Night Elf 23', path: 'night_elf23.png', race: 'night_elf' },
    { name: 'Night Elf 24', path: 'night_elf24.png', race: 'night_elf' },
    { name: 'Night Elf 25', path: 'night_elf25.png', race: 'night_elf' },
    { name: 'Night Elf 26', path: 'night_elf26.png', race: 'night_elf' },
    { name: 'Night Elf 27', path: 'night_elf27.png', race: 'night_elf' },
    { name: 'Night Elf 28', path: 'night_elf28.png', race: 'night_elf' },
    { name: 'Night Elf 29', path: 'night_elf29.png', race: 'night_elf' },
    { name: 'Night Elf 30', path: 'night_elf30.png', race: 'night_elf' },
    { name: 'Night Elf 31', path: 'night_elf31.png', race: 'night_elf' },
    { name: 'Night Elf 32', path: 'night_elf32.png', race: 'night_elf' },
    { name: 'Night Elf 33', path: 'night_elf33.png', race: 'night_elf' },
    { name: 'Night Elf 34', path: 'night_elf34.png', race: 'night_elf' },
    { name: 'Night Elf 35', path: 'night_elf35.png', race: 'night_elf' },
    { name: 'Night Elf 36', path: 'night_elf36.png', race: 'night_elf' },
    { name: 'Night Elf 37', path: 'night_elf37.png', race: 'night_elf' },
    { name: 'Night Elf 38', path: 'night_elf38.png', race: 'night_elf' },
    { name: 'Night Elf 39', path: 'night_elf39.png', race: 'night_elf' },
    { name: 'Night Elf 40', path: 'night_elf40.png', race: 'night_elf' },
    { name: 'Night Elf 41', path: 'night_elf41.png', race: 'night_elf' },
    { name: 'Night Elf 42', path: 'night_elf42.png', race: 'night_elf' },
    { name: 'Night Elf 43', path: 'night_elf43.png', race: 'night_elf' },
    { name: 'Night Elf 44', path: 'night_elf44.png', race: 'night_elf' },
    { name: 'Night Elf 45', path: 'night_elf45.png', race: 'night_elf' },
    { name: 'Night Elf 46', path: 'night_elf46.png', race: 'night_elf' },
    { name: 'Night Elf 47', path: 'night_elf47.png', race: 'night_elf' },
    { name: 'Night Elf 48', path: 'night_elf48.png', race: 'night_elf' },
  ],
};

